module.exports = {
    TOKEN_SECRET: 'my_secret_123098_token',
    permissions: {
        USER_PERMISSION: "USER_PERMISSION",
        ROLE_PERMISSION: "ROLE_PERMISSION",
        COUPON_PERMISSION: "COUPON_PERMISSION",
        PROFILE_PERMISSION: "PROFILE_PERMISSION",
        DASHBOARD_PERMISSION: "DASHBOARD_PERMISSION",
    }
}